#! /usr/bin/perl

my $header = "";
my @entries = ();
my $ent = "";
my $inheader = 1;
for (<>) {
  if ($inheader) {
     if ($_ =~ '^Discussion') {
        $inheader = 0;
     } else {
       $header .= $_;
     }
  } else {
      next if ($_ =~ /^(\}\}\}|\{\{\{)$/);
      if ($_ =~ /^[A-Z][a-z][a-z] \d\d [A-Z][a-z][a-z] \d\d\d\d \d\d:\d\d:\d\d [AP]M [A-Z][A-Z][A-Z], (original submission|comment #\d+):$/) {
         unshift @entries, $ent;
         $ent = "";
      }
      $ent .= $_;
  }
}
$ent =~ s/\A[^\n]+\n\n?(.*)\Z/Original submission:\n{{{\n\1}}}\n/sm;
$ent =~ s/\t([^\n]+)\n\Z//sm;

print "$header$ent";
for $ent (@entries) {
  my $ass = $ent =~ s/In charge of this item\.\Z//sm;
  my $mem = $ent =~ s/\nProject (Administrator|Member)\Z//sm;
  $ent =~ s/\A([^,]+), comment #(\d+):\n\n?(.*)\t([^\n]+)\n\Z/\nComment \2 by \4 at \1:\n{{{\n\3}}}\n/sm;
  print "$ent";
}

